name: "Trivy Issue Reporter"
description: "Creates GitHub Issues from Trivy scan results"
author: "Periphery Security"

inputs:
  token:
    description: "GitHub token"
    required: true
  filename:
    description: "Filename containing Trivy scan results, in JSON format"
    required: true
  labels:
    description: "Issue labels, separated by comma"
    required: false
    default: "vulnerability"
  assignees:
    description: "Issue assignees, separated by comma"
    required: false
  project-id:
    description: "Project ID to associate the issue with"
    required: false
  create-labels:
    description: "Create the labels if they don't already exist"
    required: false
    default: "false"
  enable-fix-label:
    description: "Enable adding the fix label if a fix is available"
    required: false
    default: "false"
  fix-label:
    description: "Fix label to be added if a fix is available"
    required: false
    default: "fix-available"
  dry-run:
    description: "Perform a dry run, doesnt actually create issues or labels"
    required: false
    default: "false"
    
runs:
  using: "node20" # Or the node version you are using
  main: "dist/index.js"
